name: docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          # Need to clone everything to determine version from git.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Update pip/wheel infrastructure and install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system wheel

      - name: Install documenteer
        run: uv pip install --system -r doc/requirements.txt

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Build and install
        run: uv pip install --system --no-deps -v -e .

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build -W -n

      # Only attempt documentation uploads for tagged releases and pull
      # requests from ticket branches in the same repository.  This avoids
      # version clutter in the docs and failures when a PR doesn't have access
      # to secrets.
      - name: Upload to LSST the Docs
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: "images"
          dir: "doc/_build/html"
          username: ${{ secrets.LTD_USERNAME }}
          password: ${{ secrets.LTD_PASSWORD }}
        if: >
          (github.event_name == 'push' && github.ref_name == 'main')
          || (github.event_name == 'workflow_dispatch')
          || (github.event_name == 'pull_request'
              && (startsWith(github.head_ref, 'tickets/')
                  || startsWith(github.head_ref, 'u/')))
